export const routes = [
  "Pantitlán-Zaragoza",
  "Zaragoza-Gómez Farías",
  "Gómez Farías-Boulevard Puerto Aéreo",
  "Boulevard Puerto Aéreo-Balbuena",
  "Balbuena-Moctezuma",
  "Moctezuma-San Lázaro",
  "San Lázaro-Candelaria",
  "Candelaria-Merced",
  "Merced-Pino Suárez",
  "Pino Suárez-Isabel la Católica",
  "Isabel la Católica-Salto del Agua",
  "Salto del Agua-Balderas",
  "Balderas-Cuauhtémoc",
  "Cuauhtémoc-Insurgentes",
  "Insurgentes-Sevilla",
  "Sevilla-Chapultepec",
  "Chapultepec-Juanacatlán",
  "Juanacatlán-Tacubaya",
  "Tacubaya-Observatorio",
  "Cuatro Caminos-Panteones",
  "Panteones-Tacuba",
  "Tacuba-Cuitláhuac",
  "Cuitláhuac-Popotla",
  "Popotla-Colegio Militar",
  "Colegio Militar-Normal",
  "Normal-San Cosme",
  "San Cosme-Revolución",
  "Revolución-Hidalgo",
  "Hidalgo-Bellas Artes",
  "Bellas Artes-Allende",
  "Allende-Zócalo",
  "Zócalo-Pino Suárez",
  "Pino Suárez-San Antonio Abad",
  "San Antonio Abad-Chabacano",
  "Chabacano-Viaducto",
  "Viaducto-Xola",
  "Xola-Villa de Cortés",
  "Villa de Cortés-Nativitas",
  "Nativitas-Portales",
  "Portales-Ermita",
  "Ermita-General Anaya",
  "General Anaya-Tasqueña",
  "Indios Verdes-Deportivo 18 de Marzo",
  "Deportivo 18 de Marzo-Potrero",
  "Potrero-La Raza",
  "La Raza-Tlatelolco",
  "Tlatelolco-Guerrero",
  "Guerrero-Hidalgo",
  "Hidalgo-Juárez",
  "Juárez-Balderas",
  "Balderas-Niños Héroes",
  "Niños Héroes-Hospital General",
  "Hospital General-Centro Médico",
  "Centro Médico-Etiopía/Plaza de la Transparencia",
  "Etiopía/Plaza de la Transparencia-Eugenia",
  "Eugenia-División del norte",
  "División del Norte-Zapata",
  "Zapata-Coyoacán",
  "Coyoacán-Viveros/Derechos Humanos",
  "Viveros/Derechos Humanos-Miguel Ángel de Quevedo",
  "Miguel Ángel de Quevedo-Copilco",
  "Copilco-Universidad",
  "Santa Anita-Jamaica",
  "Jamaica-Fray Servando",
  "Fray Servando-Candelaria",
  "Candelaria-Morelos",
  "Morelos-Canal del Norte",
  "Canal del Norte-Consulado",
  "Consulado-Bondojito",
  "Bondojito-Talismán",
  "Talismán-Martín Carrera",
  "Politécnico-Instituto del Petróleo",
  "Instituto del Petróleo-Autobuses del Norte",
  "Autobuses del Norte-La Raza",
  "La Raza-Misterios",
  "Misterios-Valle Gómez",
  "Valle Gómez-Consulado",
  "Consulado-Eduardo Molina",
  "Eduardo Molina-Aragón",
  "Aragón-Oceanía",
  "Oceanía-Terminal Aérea",
  "Terminal Aérea-Hangares",
  "Hangares-Pantitlán",
  "El Rosario-Tezozómoc",
  "Tezozómoc-Azcapotzalco",
  "Azcapotzalco-Ferrería",
  "Ferrería-Norte 45",
  "Norte 45-Vallejo",
  "Vallejo-Instituto del Petróleo",
  "Instituto del Petróleo-Lindavista",
  "Lindavista-Deportivo 18 de Marzo",
  "Deportivo 18 de Marzo-La Villa/Basílica",
  "La Villa/Basílica-Martín Carrera",
  "El Rosario-Aquíles Serdán",
  "Aquíles Serdán-Camarones",
  "Camarones-Refinería",
  "Refinería-Tacuba",
  "Tacuba-San Joaquín",
  "San Joaquín-Polanco",
  "Polanco-Auditorio",
  "Auditorio-Constituyentes",
  "Constituyentes-Tacubaya",
  "Tacubaya-San Pedro de los Pinos",
  "San Pedro de los Pinos-San Antonio",
  "San Antonio-Mixcoac",
  "Mixcoac-Barranca del Muerto",
  "Garibaldi-Bellas Artes",
  "Bellas Artes-San Juan de Letrán",
  "San Juan de Letrán-Salto del Agua",
  "Salto del Agua-Doctores",
  "Doctores-Obrera",
  "Obrera-Chabacano",
  "Chabacano-La Viga",
  "La Viga-Santa Anita",
  "Santa Anita-Coyuya",
  "Coyuya-Iztacalco",
  "Iztacalco-Apatlaco",
  "Apatlaco-Aculco",
  "Aculco-Escuadrón 201",
  "Escuadrón 201-Atlalilco",
  "Atlalilco-Iztapalapa",
  "Iztapalapa-Cerro de la Estrella",
  "Cerro de la Estrella-UAM I",
  "UAM I-Constitución de 1917",
  "Pantitlán-Puebla",
  "Puebla-Ciudad Deportiva",
  "Ciudad Deportiva-Velódromo",
  "Velódromo-Mixiuhca",
  "Mixiuhca-Jamaica",
  "Jamaica-Chabacano",
  "Chabacano-Lázaro Cardenas",
  "Lázaro Cardenas-Centro Médico",
  "Centro Médico-Chilpancingo",
  "Chilpancingo-Patriotismo",
  "Patriotismo-Tacubaya",
  "Pantitlán-Agrícola Oriental",
  "Agrícola Oriental-Canal de San Juan",
  "Canal de San Juan-Tepalcates",
  "Tepalcates-Guelatao",
  "Guelatao-Peñón Viejo",
  "Peñón Viejo-Acatitla",
  "Acatitla-Santa Marta",
  "Santa Marta-Los Reyes",
  "Los Reyes-La Paz",
  "Ciudad Azteca-Plaza Aragón",
  "Plaza Aragón-Olímpica",
  "Olímpica-Ecatepec",
  "Ecatepec-Múzquiz",
  "Múzquiz-Río de los Remedios",
  "Río de los Remedios-Impulsora",
  "Impulsora-Nezahualcóyotl",
  "Nezahualcóyotl-Villa de Aragón",
  "Villa de Aragón-Bosques de Aragón",
  "Bosques de Aragón-Deportivo Oceanía",
  "Deportivo Oceanía-Oceanía",
  "Oceanía-Romero Rubio",
  "Romero Rubio-Ricardo Flores Magón",
  "Ricardo Flores Magón-San Lázaro",
  "San Lázaro-Morelos",
  "Morelos-Tepito",
  "Tepito-Lagunilla",
  "Lagunilla-Garibaldi",
  "Garibaldi-Guerrero",
  "Guerrero-Buenavista",
  "Tláhuac-Tlaltenco ",
  "Tlaltenco-Zapotitlán",
  "Zapotitlán-Nopalera",
  "Nopalera-Olivos",
  "Olivos-Tezonco",
  "Tezonco-Periférico Oriente",
  "Periférico Oriente-Calle 11",
  "Calle 11-Lomas Estrella",
  "Lomas Estrella-San Andrés Tomatlán",
  "San Andrés Tomatlán-Culhuacán",
  "Culhuacán-Atlalilco",
  "Atlalilco-Mexicaltzingo",
  "Mexicaltzingo-Ermita",
  "Ermita-Eje Central",
  "Eje Central-Parque de los Venados",
  "Parque de los Venados-Zapata",
  "Zapata-Hospital 20 de Noviembre",
  "Hospital 20 de Noviembre-Insurgentes Sur",
  "Insurgentes Sur-Mixcoac",
]