const stations = [
  "Pantitlán Línea 1-Zaragoza",
  "Pantitlán Línea 1-Pantitlán Línea 5",
  "Pantitlán Línea 1-Pantitlán Línea 9",
  "Pantitlán Línea 1-Pantitlán Línea A",
  "Zaragoza-Gómez Farías",
  "Gómez Farías-Boulevard Puerto Aéreo",
  "Boulevard Puerto Aéreo-Balbuena",
  "Balbuena-Moctezuma",
  "Moctezuma-San Lázaro Línea 1",
  "San Lázaro Línea 1-Candelaria Línea 1",
  "San Lázaro Línea 1-San Lázaro Línea B",
  "Candelaria Línea 1-Merced",
  "Candelaria Línea 1-Candelaria Línea 4",
  "Merced-Pino Suárez Línea 1",
  "Pino Suárez Línea 1-Isabel la Católica",
  "Pino Suárez Línea 1-Pino Suárez Línea 2",
  "Isabel la Católica-Salto del Agua Línea 1",
  "Salto del Agua Línea 1-Balderas Línea 1",
  "Salto del Agua Línea 1-Salto del Agua Línea 8",
  "Balderas Línea 1-Cuauhtémoc",
  "Balderas Línea 1-Balderas Línea 3",
  "Cuauhtémoc-Insurgentes",
  "Insurgentes-Sevilla",
  "Sevilla-Chapultepec",
  "Chapultepec-Juanacatlán",
  "Juanacatlán-Tacubaya Línea 1",
  "Tacubaya Línea 1-Observatorio",
  "Tacubaya Línea 1-Tacubaya Línea 9",
  "Tacubaya Línea 1-Tacubaya Línea 7",
  "Cuatro Caminos-Panteones",
  "Panteones-Tacuba Línea 2",
  "Tacuba Línea 2-Cuitláhuac",
  "Cuitláhuac-Popotla",
  "Popotla-Colegio Militar",
  "Colegio Militar-Normal",
  "Normal-San Cosme",
  "San Cosme-Revolución",
  "Revolución-Hidalgo Línea 2",
  "Hidalgo Línea 2-Bellas Artes Línea 2",
  "Hidalgo Línea 2-Hidalgo Línea 3",
  "Bellas Artes Línea 2-Allende",
  "Bellas Artes Línea 2-Bellas Artes Línea 8",
  "Allende-Zócalo",
  "Zócalo-Pino Suárez Línea 2",
  "Pino Suárez Línea 2-San Antonio Abad",
  "Pino Suárez Línea 2-Pino Suárez Línea 1",
  "San Antonio Abad-Chabacano Línea 2",
  "Chabacano Línea 2-Viaducto",
  "Chabacano Línea 2-Chabacano Línea 8",
  "Chabacano Línea 2-Chabacano Línea 9",
  "Viaducto-Xola",
  "Xola-Villa de Cortés",
  "Villa de Cortés-Nativitas",
  "Nativitas-Portales",
  "Portales-Ermita Línea 2",
  "Ermita Línea 2-General Anaya",
  "Ermita Línea 2-Ermita Línea 12",
  "General Anaya-Tasqueña",
  "Indios Verdes-Deportivo 18 de Marzo Línea 3",
  "Deportivo 18 de Marzo Línea 3-Potrero",
  "Deportivo 18 de Marzo Línea 3-Deportivo 18 de Marzo Línea 6",
  "Potrero-La Raza Línea 3",
  "La Raza Línea 3-Tlatelolco",
  "La Raza Línea 3-La Raza Línea 5",
  "Tlatelolco-Guerrero Línea 3",
  "Guerrero Línea 3-Hidalgo Línea 3",
  "Guerrero Línea 3-Guerrero Línea B",
  "Hidalgo Línea 3-Juárez",
  "Juárez-Balderas Línea 3",
  "Balderas Línea 3-Niños Héroes",
  "Balderas Línea 3-Balderas Línea 1",
  "Niños Héroes-Hospital General",
  "Hospital General-Centro Médico Línea 3",
  "Centro Médico Línea 3-Etiopía/Plaza de la Transparencia",
  "Centro Médico Línea 3-Centro Médico Línea 9",
  "Etiopía/Plaza de la Transparencia-Eugenia",
  "Eugenia-División del norte",
  "División del Norte-Zapata Línea 3",
  "Zapata Línea 3-Coyoacán",
  "Zapata Línea 3-Zapata Línea 12",
  "Coyoacán-Viveros/Derechos Humanos",
  "Viveros/Derechos Humanos-Miguel Ángel de Quevedo",
  "Miguel Ángel de Quevedo-Copilco",
  "Copilco-Universidad",
  "Santa Anita Línea 4-Santa Anita Línea 8",
  "Santa Anita Línea 4-Jamaica Línea 4",
  "Jamaica Línea 4-Fray Servando",
  "Jamaica Línea 4-Jamaica Línea 9",
  "Fray Servando-Candelaria Línea 4",
  "Candelaria Línea 4-Morelos Línea 4",
  "Candelaria Línea 4-Candelaria Línea 1",
  "Morelos Línea 4-Canal del Norte",
  "Morelos Línea 4-Morelos Línea B",
  "Canal del Norte-Consulado Línea 4",
  "Consulado Línea 4-Bondojito",
  "Consulado Línea 4-Consulado Línea 5",
  "Bondojito-Talismán",
  "Talismán-Martín Carrera Línea 4",
  "Politécnico-Instituto del Petróleo Línea 5",
  "Instituto del Petróleo Línea 5-Autobuses del Norte",
  "Instituto del Petróleo Línea 5-Instituto del Petróleo Línea 6",
  "Autobuses del Norte-La Raza Línea 5",
  "La Raza Línea 5-Misterios",
  "Misterios-Valle Gómez",
  "Valle Gómez-Consulado Linea 5",
  "Consulado Línea 5-Eduardo Molina",
  "Consulado Línea 5-Consulado Línea 4",
  "Eduardo Molina-Aragón",
  "Aragón-Oceanía Línea 5",
  "Oceanía Línea 5-Terminal Aérea",
  "Oceanía Línea 5-Oceanía Línea B",
  "Terminal Aérea-Hangares",
  "Hangares-Pantitlán Línea 5",
  "Pantitlán Línea 5-Pantitlán Línea 1",
  "Pantitlán Línea 5-Pantitlán Línea 9",
  "Pantitlán Línea 5-Pantitlán Línea A",
  "El Rosario Línea 6-Tezozómoc",
  "El Rosario Línea 6-El Rosario Línea 7",
  "Tezozómoc-Azcapotzalco",
  "Azcapotzalco-Ferrería",
  "Ferrería-Norte 45",
  "Norte 45-Vallejo",
  "Vallejo-Instituto del Petróleo Línea 6",
  "Instituto del Petróleo Línea 6-Lindavista",
  "Lindavista-Deportivo 18 de Marzo Línea 6",
  "Deportivo 18 de Marzo Línea 6-La Villa/Basílica",
  "Martín Carrera Línea 6-Martín Carrera Línea 4",
  "El Rosario Línea 7-Aquíles Serdán",
  "Aquíles Serdán-Camarones",
  "Camarones-Refinería",
  "Refinería-Tacuba Línea 7",
  "Tacuba Línea 7-San Joaquín",
  "Tacuba Línea 7-Tacuba Línea 2",
  "San Joaquín-Polanco",
  "Polanco-Auditorio",
  "Auditorio-Constituyentes",
  "Constituyentes-Tacubaya Línea 7",
  "Tacubaya Línea 7-San Pedro de los Pinos",
  "Tacubaya Línea 7-Tacubaya Línea 9",
  "Tacubaya Línea 7-Tacubaya Línea 1",
  "San Pedro de los Pinos-San Antonio",
  "San Antonio-Mixcoac",
  "Mixcoac-Barranca del Muerto",
  "Mixcoac Línea 7-Mixcoac Línea 12",
  "Garibaldi Línea 8-Bellas Artes Línea 8",
  "Garibaldi Línea 8-Garibaldi Línea B",
  "Bellas Artes Línea 8-San Juan de Letrán",
  "San Juan de Letrán-Salto del Agua Línea 8",
  "Salto del Agua Línea 8-Doctores",
  "Salto del Agua Línea 8-Salto del Agua Línea 1",
  "Doctores-Obrera",
  "Obrera-Chabacano Línea 8",
  "Chabacano Línea 8-La Viga",
  "Chabacano Línea 8-Chabacano Línea 2",
  "Chabacano Línea 8-Chabacano Línea 9",
  "La Viga-Santa Anita Línea 8",
  "Santa Anita Línea 8-Coyuya",
  "Santa Anita Línea 8-Santa Anita Línea 4",
  "Coyuya-Iztacalco",
  "Iztacalco-Apatlaco",
  "Apatlaco-Aculco",
  "Aculco-Escuadrón 201",
  "Escuadrón 201-Atlalilco Línea 8",
  "Atlalilco Línea 8-Iztapalapa",
  "Atlalilco Línea 8-Atlalilco Línea 12",
  "Iztapalapa-Cerro de la Estrella",
  "Cerro de la Estrella-UAM I",
  "UAM I-Constitución de 1917",
  "Pantitlán Línea 9-Puebla",
  "Pantitlán Línea 9-Pantitlán Línea 1",
  "Pantitlán Línea 9-Pantitlán Línea 5",
  "Pantitlán Línea 9-Pantitlán Línea A",
  "Puebla-Ciudad Deportiva",
  "Ciudad Deportiva-Velódromo",
  "Velódromo-Mixiuhca",
  "Mixiuhca-Jamaica Línea 9",
  "Jamaica Línea 9-Chabacano Línea 9",
  "Jamaica Línea 9-Jamaica Línea 4",
  "Chabacano Línea 9-Lázaro Cardenas",
  "Chabacano Línea 9-Chabacano Línea 2",
  "Chabacano Línea 9-Chabacano Línea 8",
  "Lázaro Cardenas-Centro Médico Línea 9",
  "Centro Médico Línea 9-Chilpancingo",
  "Centro Médico Línea 9-Centro Médico Línea 3",
  "Chilpancingo-Patriotismo",
  "Patriotismo-Tacubaya Línea 9",
  "Tacubaya Línea 9-Tacubaya Línea 1",
  "Tacubaya Línea 9-Tacubaya Línea 7",
  "Pantitlán Línea A-Agrícola Oriental",
  "Pantitlán Línea A-Pantitlán Línea 1",
  "Pantitlán Línea A-Pantitlán Línea 5",
  "Pantitlán Línea A-Pantitlán Línea 9",
  "Agrícola Oriental-Canal de San Juan",
  "Canal de San Juan-Tepalcates",
  "Tepalcates-Guelatao",
  "Guelatao-Peñón Viejo",
  "Peñón Viejo-Acatitla",
  "Acatitla-Santa Marta",
  "Santa Marta-Los Reyes",
  "Los Reyes-La Paz",
  "Ciudad Azteca-Plaza Aragón",
  "Plaza Aragón-Olímpica",
  "Olímpica-Ecatepec",
  "Ecatepec-Múzquiz",
  "Múzquiz-Río de los Remedios",
  "Río de los Remedios-Impulsora",
  "Impulsora-Nezahualcóyotl",
  "Nezahualcóyotl-Villa de Aragón",
  "Villa de Aragón-Bosques de Aragón",
  "Bosques de Aragón-Deportivo Oceanía",
  "Deportivo Oceanía-Oceanía Línea B",
  "Oceanía Línea B-Romero Rubio",
  "Oceanía Línea B-Oceanía Línea 5",
  "Romero Rubio-Ricardo Flores Magón",
  "Ricardo Flores Magón-San Lázaro Línea B",
  "San Lázaro Línea B-San Lázaro Línea 1",
  "San Lázaro Línea B-Morelos Línea B",
  "Morelos Línea B-Morelos Línea 4",
  "Morelos Línea B-Tepito",
  "Tepito-Lagunilla",
  "Lagunilla-Garibaldi Línea B",
  "Garibaldi Línea B-Guerrero Línea B",
  "Garibaldi Línea B-Garibaldi Línea 8",
  "Guerrero Línea B-Buenavista",
  "Tláhuac-Tlaltenco ",
  "Tlaltenco-Zapotitlán",
  "Zapotitlán-Nopalera",
  "Nopalera-Olivos",
  "Olivos-Tezonco",
  "Tezonco-Periférico Oriente",
  "Periférico Oriente-Calle 11",
  "Calle 11-Lomas Estrella",
  "Lomas Estrella-San Andrés Tomatlán",
  "San Andrés Tomatlán-Culhuacán",
  "Culhuacán-Atlalilco Línea 12",
  "Atlalilco Línea 12-Mexicaltzingo",
  "Atlalilco Línea 8-Atlalilco Línea 12",
  "Mexicaltzingo-Ermita Línea 12",
  "Ermita Línea 12-Eje Central",
  "Ermita Línea 12-Ermita Línea 2",
  "Eje Central-Parque de los Venados",
  "Parque de los Venados-Zapata Línea 12",
  "Zapata Línea 12-Hospital 20 de Noviembre",
  "Zapata Línea 12-Zapata Línea 3",
  "Hospital 20 de Noviembre-Insurgentes Sur",
  "Insurgentes Sur-Mixcoac Línea 12",
  "Mixcoac Línea 12-Mixcoac Línea 7",
]

const routes = stations.filter((i) => i.includes('-'))

module.exports = routes